//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task4.StudentsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://www.friends.com/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private float AvgMarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float AvgMark {
            get {
                return this.AvgMarkField;
            }
            set {
                if ((this.AvgMarkField.Equals(value) != true)) {
                    this.AvgMarkField = value;
                    this.RaisePropertyChanged("AvgMark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.friends.com/", ConfigurationName="StudentsService.StudentsServiceSoap")]
    public interface StudentsServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllStudentsResult from namespace http://www.friends.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.friends.com/GetAllStudents", ReplyAction="*")]
        Task4.StudentsService.GetAllStudentsResponse GetAllStudents(Task4.StudentsService.GetAllStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.friends.com/GetAllStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<Task4.StudentsService.GetAllStudentsResponse> GetAllStudentsAsync(Task4.StudentsService.GetAllStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetStudentsFilteredByAverageMarkResult from namespace http://www.friends.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.friends.com/GetStudentsFilteredByAverageMark", ReplyAction="*")]
        Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse GetStudentsFilteredByAverageMark(Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.friends.com/GetStudentsFilteredByAverageMark", ReplyAction="*")]
        System.Threading.Tasks.Task<Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse> GetStudentsFilteredByAverageMarkAsync(Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudents", Namespace="http://www.friends.com/", Order=0)]
        public Task4.StudentsService.GetAllStudentsRequestBody Body;
        
        public GetAllStudentsRequest() {
        }
        
        public GetAllStudentsRequest(Task4.StudentsService.GetAllStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStudentsRequestBody {
        
        public GetAllStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentsResponse", Namespace="http://www.friends.com/", Order=0)]
        public Task4.StudentsService.GetAllStudentsResponseBody Body;
        
        public GetAllStudentsResponse() {
        }
        
        public GetAllStudentsResponse(Task4.StudentsService.GetAllStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.friends.com/")]
    public partial class GetAllStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Task4.StudentsService.Student[] GetAllStudentsResult;
        
        public GetAllStudentsResponseBody() {
        }
        
        public GetAllStudentsResponseBody(Task4.StudentsService.Student[] GetAllStudentsResult) {
            this.GetAllStudentsResult = GetAllStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsFilteredByAverageMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsFilteredByAverageMark", Namespace="http://www.friends.com/", Order=0)]
        public Task4.StudentsService.GetStudentsFilteredByAverageMarkRequestBody Body;
        
        public GetStudentsFilteredByAverageMarkRequest() {
        }
        
        public GetStudentsFilteredByAverageMarkRequest(Task4.StudentsService.GetStudentsFilteredByAverageMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.friends.com/")]
    public partial class GetStudentsFilteredByAverageMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float lowerBound;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float upperBound;
        
        public GetStudentsFilteredByAverageMarkRequestBody() {
        }
        
        public GetStudentsFilteredByAverageMarkRequestBody(float lowerBound, float upperBound) {
            this.lowerBound = lowerBound;
            this.upperBound = upperBound;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentsFilteredByAverageMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentsFilteredByAverageMarkResponse", Namespace="http://www.friends.com/", Order=0)]
        public Task4.StudentsService.GetStudentsFilteredByAverageMarkResponseBody Body;
        
        public GetStudentsFilteredByAverageMarkResponse() {
        }
        
        public GetStudentsFilteredByAverageMarkResponse(Task4.StudentsService.GetStudentsFilteredByAverageMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.friends.com/")]
    public partial class GetStudentsFilteredByAverageMarkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Task4.StudentsService.Student[] GetStudentsFilteredByAverageMarkResult;
        
        public GetStudentsFilteredByAverageMarkResponseBody() {
        }
        
        public GetStudentsFilteredByAverageMarkResponseBody(Task4.StudentsService.Student[] GetStudentsFilteredByAverageMarkResult) {
            this.GetStudentsFilteredByAverageMarkResult = GetStudentsFilteredByAverageMarkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentsServiceSoapChannel : Task4.StudentsService.StudentsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsServiceSoapClient : System.ServiceModel.ClientBase<Task4.StudentsService.StudentsServiceSoap>, Task4.StudentsService.StudentsServiceSoap {
        
        public StudentsServiceSoapClient() {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task4.StudentsService.GetAllStudentsResponse Task4.StudentsService.StudentsServiceSoap.GetAllStudents(Task4.StudentsService.GetAllStudentsRequest request) {
            return base.Channel.GetAllStudents(request);
        }
        
        public Task4.StudentsService.Student[] GetAllStudents() {
            Task4.StudentsService.GetAllStudentsRequest inValue = new Task4.StudentsService.GetAllStudentsRequest();
            inValue.Body = new Task4.StudentsService.GetAllStudentsRequestBody();
            Task4.StudentsService.GetAllStudentsResponse retVal = ((Task4.StudentsService.StudentsServiceSoap)(this)).GetAllStudents(inValue);
            return retVal.Body.GetAllStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task4.StudentsService.GetAllStudentsResponse> Task4.StudentsService.StudentsServiceSoap.GetAllStudentsAsync(Task4.StudentsService.GetAllStudentsRequest request) {
            return base.Channel.GetAllStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task4.StudentsService.GetAllStudentsResponse> GetAllStudentsAsync() {
            Task4.StudentsService.GetAllStudentsRequest inValue = new Task4.StudentsService.GetAllStudentsRequest();
            inValue.Body = new Task4.StudentsService.GetAllStudentsRequestBody();
            return ((Task4.StudentsService.StudentsServiceSoap)(this)).GetAllStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse Task4.StudentsService.StudentsServiceSoap.GetStudentsFilteredByAverageMark(Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest request) {
            return base.Channel.GetStudentsFilteredByAverageMark(request);
        }
        
        public Task4.StudentsService.Student[] GetStudentsFilteredByAverageMark(float lowerBound, float upperBound) {
            Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest inValue = new Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest();
            inValue.Body = new Task4.StudentsService.GetStudentsFilteredByAverageMarkRequestBody();
            inValue.Body.lowerBound = lowerBound;
            inValue.Body.upperBound = upperBound;
            Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse retVal = ((Task4.StudentsService.StudentsServiceSoap)(this)).GetStudentsFilteredByAverageMark(inValue);
            return retVal.Body.GetStudentsFilteredByAverageMarkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse> Task4.StudentsService.StudentsServiceSoap.GetStudentsFilteredByAverageMarkAsync(Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest request) {
            return base.Channel.GetStudentsFilteredByAverageMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task4.StudentsService.GetStudentsFilteredByAverageMarkResponse> GetStudentsFilteredByAverageMarkAsync(float lowerBound, float upperBound) {
            Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest inValue = new Task4.StudentsService.GetStudentsFilteredByAverageMarkRequest();
            inValue.Body = new Task4.StudentsService.GetStudentsFilteredByAverageMarkRequestBody();
            inValue.Body.lowerBound = lowerBound;
            inValue.Body.upperBound = upperBound;
            return ((Task4.StudentsService.StudentsServiceSoap)(this)).GetStudentsFilteredByAverageMarkAsync(inValue);
        }
    }
}
